"""Setup Fabric workspaces and update workspaces.yml with their IDs.

This script ensures all required Fabric workspaces exist and updates the
workspaces.yml configuration file with their actual workspace IDs.

Workspace naming convention: {solution_name}-{workspace_type}-{environment}
Solution name: main
Examples: main-ingestion-dev, main-lakehouse-prd, main-lakehouse_processing-tst

Local usage:
    az login
    python setup_workspaces.py

This will:
1. List all accessible Fabric workspaces
2. Create missing workspaces based on workspaces.yml structure
3. Update workspaces.yml with actual workspace IDs
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import requests
import yaml

from fabric_client import FabricClient, load_workspace_config, load_solution_config, WORKSPACES_CONFIG


class FabricWorkspaceManager(FabricClient):
    """Manage Fabric workspaces via REST API."""

    def list_workspaces(self) -> dict[str, str]:
        """List all accessible workspaces.
        
        Returns:
            Dict mapping workspace name to workspace ID
        """
        result = self._api_request("GET", "/workspaces")
        workspaces = {}
        
        for workspace in result.get("value", []):
            workspaces[workspace["displayName"]] = workspace["id"]
        
        return workspaces

    def create_workspace(self, name: str, description: str = "", capacity_id: str | None = None) -> str:
        """Create a new workspace.
        
        Args:
            name: Workspace display name
            description: Optional workspace description
            capacity_id: Optional Fabric capacity ID to assign workspace to
            
        Returns:
            Workspace ID
            
        Raises:
            RuntimeError: If workspace creation fails or returns no ID
        """
        payload = {
            "displayName": name,
        }
        if description:
            payload["description"] = description
        if capacity_id and capacity_id != "REPLACE_WITH_YOUR_CAPACITY_ID":
            payload["capacityId"] = capacity_id
            print(f"  → Assigning to capacity: {capacity_id}")
        
        print(f"  → Calling Fabric API to create workspace '{name}'...")
        
        try:
            result = self._api_request("POST", "/workspaces", json_data=payload)
        except requests.exceptions.HTTPError as e:
            print(f"\n❌ FAILED to create workspace '{name}'")
            print(f"   HTTP Error: {e}")
            print(f"   This usually means:")
            print(f"   1. Service principal lacks 'Workspace creation' permission")
            print(f"   2. Tenant setting 'Service principals can use Fabric APIs' is disabled")
            print(f"   3. Service principal is not in an enabled security group")
            if capacity_id:
                print(f"   4. Invalid capacity ID or no permission on capacity")
            raise
        
        workspace_id = result.get("id")
        
        if not workspace_id:
            raise RuntimeError(f"Failed to create workspace '{name}': no ID returned from API")
        
        print(f"✓ Created workspace: {name} ({workspace_id})")
        return workspace_id

    def get_or_create_workspace(self, name: str, description: str = "", capacity_id: str | None = None) -> str:
        """Get existing workspace ID or create new workspace.
        
        Args:
            name: Workspace display name
            description: Optional workspace description
            capacity_id: Optional Fabric capacity ID to assign workspace to
            
        Returns:
            Workspace ID
        """
        workspaces = self.list_workspaces()
        
        if name in workspaces:
            workspace_id = workspaces[name]
            print(f"✓ Found existing workspace: {name} ({workspace_id})")
            return workspace_id
        
        return self.create_workspace(name, description, capacity_id)


def save_workspace_config(config: dict, solution_name: str, capacity_config: dict | None = None, config_path: Path = WORKSPACES_CONFIG) -> None:
    """Save workspace configuration to lakehouse_solution.yml.
    
    Preserves non-environment properties like 'lakehouses' lists and capacity settings.
    """
    full_config = {
        "solution_name": solution_name,
    }
    
    # Add capacity configuration if provided
    if capacity_config:
        full_config["capacity"] = capacity_config
    
    full_config["workspaces"] = config
    
    with config_path.open("w", encoding="utf-8") as fh:
        # Write header comment
        fh.write("# Fabric lakehouse solution configuration\n")
        fh.write("# Auto-generated by setup_workspaces.py\n")
        fh.write("# Workspace naming: {solution_name}-{workspace_type}-{environment}\n")
        fh.write("# Values may be overridden at runtime via env vars.\n\n")
        
        # Write YAML content
        yaml.safe_dump(
            full_config,
            fh,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
    
    print(f"\n✓ Updated {config_path}")


def setup_workspaces(dry_run: bool = False) -> None:
    """Setup all workspaces and update configuration."""
    # Load current workspace configuration
    full_config = load_solution_config()
    solution_name = full_config.get("solution_name", "main")
    config = full_config.get("workspaces", {})
    capacity_config = full_config.get("capacity", {})
    
    manager = FabricWorkspaceManager()
    
    print("Setting up Fabric workspaces...")
    print(f"Configuration file: {WORKSPACES_CONFIG}")
    
    # Show capacity configuration
    if capacity_config:
        print("\nCapacity configuration:")
        for env, cap_id in capacity_config.items():
            if cap_id != "REPLACE_WITH_YOUR_CAPACITY_ID":
                print(f"  {env}: {cap_id}")
            else:
                print(f"  {env}: (not configured - will use trial/default)")
    else:
        print("\n⚠️  No capacity configuration found - workspaces will use trial/default capacity")
    
    print()
    
    # Fetch existing workspaces from Fabric API
    print("Fetching existing workspaces from Fabric...")
    try:
        existing_workspaces = manager.list_workspaces()
        print(f"Found {len(existing_workspaces)} existing workspace(s)")
        
        if existing_workspaces:
            print("Existing workspaces:")
            for name, ws_id in list(existing_workspaces.items())[:5]:
                print(f"  - {name} ({ws_id})")
            if len(existing_workspaces) > 5:
                print(f"  ... and {len(existing_workspaces) - 5} more")
        else:
            print("\n⚠️  WARNING: No workspaces found!")
            print("   This could mean:")
            print("   1. Service principal can't list workspaces (permission issue)")
            print("   2. No workspaces exist yet (expected on first run)")
            print("   3. Service principal doesn't have Viewer access to any workspace\n")
    except requests.exceptions.HTTPError as e:
        print(f"\n❌ FAILED to list workspaces from Fabric API")
        print(f"   HTTP Error: {e}")
        print(f"   Check service principal permissions!")
        raise
    
    print()
    updated = False
    
    for workspace_type, environments in config.items():
        if not isinstance(environments, dict):
            continue  # Skip non-workspace entries
        
        print(f"\n--- Workspace type: {workspace_type} ---")
        
        for environment, current_id in environments.items():
            # Skip non-environment properties (e.g., 'lakehouses' lists)
            if not isinstance(current_id, str):
                continue
            
            # Generate workspace name following convention
            workspace_name = f"{solution_name}-{workspace_type}-{environment}"
            
            # Check if workspace exists in Fabric
            workspace_exists_in_fabric = workspace_name in existing_workspaces
            
            print(f"\n{workspace_name}:")
            print(f"  Config ID: {current_id}")
            
            if workspace_exists_in_fabric:
                # Workspace exists in Fabric - verify/update ID
                actual_id = existing_workspaces[workspace_name]
                print(f"  Fabric ID: {actual_id}")
                
                if current_id != actual_id:
                    print(f"  ⚠️  ID mismatch detected!")
                    if not dry_run:
                        config[workspace_type][environment] = actual_id
                        updated = True
                        print(f"  ✓ Updated config with actual ID")
                    else:
                        print(f"  [DRY RUN] Would update config with actual ID")
                else:
                    print(f"  ✓ ID matches - no update needed")
            else:
                # Workspace doesn't exist in Fabric - create it
                print(f"  Fabric ID: (not found)")
                
                if not dry_run:
                    description = f"{workspace_type.replace('_', ' ').title()} workspace for {environment.upper()} environment"
                    
                    # Get capacity ID for this environment
                    capacity_id = capacity_config.get(environment) if capacity_config else None
                    
                    workspace_id = manager.create_workspace(workspace_name, description, capacity_id)
                    
                    # Update configuration with the new ID
                    config[workspace_type][environment] = workspace_id
                    updated = True
                    print(f"  ✓ Created and updated config")
                else:
                    print(f"  [DRY RUN] Would create workspace: {workspace_name}")
    
    # Save updated configuration
    if updated and not dry_run:
        save_workspace_config(config, solution_name, capacity_config)
        print("\n✅ All workspaces configured successfully!")
    elif dry_run:
        print("\n✅ Dry run completed. Use without --dry-run to apply changes.")
    else:
        print("\n✅ All workspaces already configured.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Setup Fabric workspaces and update lakehouse_solution.yml"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without making changes",
    )
    args = parser.parse_args(argv)

    try:
        setup_workspaces(dry_run=args.dry_run)
        return 0
    except Exception as e:
        print(f"\n❌ Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
